export const COLORS = {
  gold: '#c8a96e',
  goldLight: '#fdf6ec',
  goldMid: '#f0d9b5',
  goldDark: '#a07c3e',
  dark: '#1a1a1a',
  dark2: '#2a2a2a',
  white: '#ffffff',
  offWhite: '#f8f7f4',
  beige: '#e8e4de',
  beigeMid: '#d4cdc4',
  gray: '#888888',
  grayLight: '#f0ece8',
  grayDark: '#555555',
  success: '#22c55e',
  successBg: '#f0faf0',
  successBorder: '#c0e0c0',
  successText: '#2d6a32',
  warning: '#f0d9b5',
  warningBg: '#fff8f0',
  warningText: '#8a6020',
  stripePurple: '#635bff',
  border: '#e8e4de',
};

export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || 'https://api.evidence-homestaging.fr';
export const STRIPE_PUBLISHABLE_KEY = process.env.EXPO_PUBLIC_STRIPE_KEY || 'pk_live_XXXX';
export const FREE_TRIAL_COOLDOWN_HOURS = 24;

export const FORMULAS = {
  // BIENS VIDES — "PROJECTION"
  decouverte: {
    id: 'decouverte',
    name: 'Découverte',
    price: 39.00,
    priceHT: 32.50,
    tva: 6.50,
    maxPhotos: 2,
    type: 'vide',
    features: [
      '2 photos maximum',
      'Avant / Après',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Facture automatique',
    ],
    popular: false,
    instantResult: true,
  },
  essentielle: {
    id: 'essentielle',
    name: 'Essentielle',
    price: 89.00,
    priceHT: 74.17,
    tva: 14.83,
    maxPhotos: 5,
    type: 'vide',
    features: [
      '5 photos maximum',
      'Avant / Après',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Facture automatique',
    ],
    popular: false,
    instantResult: true,
  },
  performance: {
    id: 'performance',
    name: 'Performance',
    price: 139.00,
    priceHT: 115.83,
    tva: 23.17,
    maxPhotos: 8,
    type: 'vide',
    features: [
      'Jusqu\'à 8 photos maximum',
      'Avant / Après',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Max impact annonce',
      'Facture automatique',
    ],
    popular: true,
    instantResult: true,
  },

  // BIENS HABITÉS — "OPTIMISATION"
  essentielHabite: {
    id: 'essentiel_habite',
    name: 'Essentiel',
    price: 79.00,
    priceHT: 65.83,
    tva: 13.17,
    maxRooms: 2,
    type: 'habite',
    features: [
      'Analyse jusqu\'à 2 pièces',
      'Rapport PDF personnalisé',
      'Conseils pièce par pièce',
      'Projection directe sur vos photos',
      'Optimisation vente rapide',
      'Facture automatique',
      'Résultat sous 48-72h',
    ],
    popular: false,
    deliveryTime: '48-72h',
  },
  premiumHabite: {
    id: 'premium_habite',
    name: 'Premium',
    price: 159.00,
    priceHT: 132.50,
    tva: 26.50,
    maxRooms: 5,
    type: 'habite',
    features: [
      'Analyse jusqu\'à 5 pièces',
      'Rapport PDF personnalisé',
      'Conseils pièce par pièce',
      'Projection directe sur vos photos',
      'Optimisation vente rapide',
      'Facture automatique',
      'Résultat sous 72h',
    ],
    popular: true,
    deliveryTime: '72h',
  },
};