export const FORMULAS = {
  // BIENS VIDES — "PROJECTION"
  decouverte: {
    id: 'decouverte',
    name: 'Découverte',
    price: 39.00,
    priceHT: 32.50,
    tva: 6.50,
    maxPhotos: 2,
    type: 'vide',
    features: [
      '2 photos maximum',
      'Avant / Après IA réaliste',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Facture automatique',
    ],
    popular: false,
    instantResult: true,
  },
  essentielle: {
    id: 'essentielle',
    name: 'Essentielle',
    price: 89.00,
    priceHT: 74.17,
    tva: 14.83,
    maxPhotos: 5,
    type: 'vide',
    features: [
      '5 photos maximum',
      'Avant / Après IA réaliste',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Facture automatique',
    ],
    popular: false,
    instantResult: true,
  },
  performance: {
    id: 'performance',
    name: 'Performance',
    price: 139.00,
    priceHT: 115.83,
    tva: 23.17,
    maxPhotos: 8,
    type: 'vide',
    features: [
      'Jusqu\'à 8 photos maximum',
      'Avant / Après IA réaliste',
      '3 conseils actionnables',
      'Multi-vue (Salon & Chambre)',
      'Téléchargement HD illimité',
      'Visuels contrôlés et optimisés',
      'Résultat sous 2-12h',
      'Max impact annonce',
      'Facture automatique',
    ],
    popular: true,
    instantResult: true,
  },

  // BIENS HABITÉS — "OPTIMISATION"
  essentielHabite: {
    id: 'essentiel_habite',
    name: 'Essentiel',
    price: 79.00,
    priceHT: 65.83,
    tva: 13.17,
    maxRooms: 2,
    type: 'habite',
    features: [
      'Analyse jusqu\'à 2 pièces',
      'Rapport PDF personnalisé',
      'Conseils pièce par pièce',
      'Projection directe sur vos photos',
      'Optimisation vente rapide',
      'Facture automatique',
      'Résultat sous 48-72h',
    ],
    popular: false,
    deliveryTime: '48-72h',
  },
  premiumHabite: {
    id: 'premium_habite',
    name: 'Premium',
    price: 159.00,
    priceHT: 132.50,
    tva: 26.50,
    maxRooms: 5,
    type: 'habite',
    features: [
      'Analyse jusqu\'à 5 pièces',
      'Rapport PDF personnalisé',
      'Conseils pièce par pièce',
      'Projection directe sur vos photos',
      'Optimisation vente rapide',
      'Facture automatique',
      'Résultat sous 72h',
    ],
    popular: true,
    deliveryTime: '72h',
  },
};